In [1]:
import torch

In [2]:
t1 = torch.tensor([[1,2,3],[4,5,6]])

In [3]:
t1.view(-1,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [4]:
t1.reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [5]:
t1.reshape(-1,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
t1.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [7]:
t1.is_contiguous()

True

In [8]:
t1.contiguous()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
t1.storage()

C:\Users\User\AppData\Local\Temp\ipykernel_16444\2472056026.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  t1.storage()


 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [11]:
t1.storage_offset()

0

In [12]:
t1.stride()

(3, 1)

In [13]:
t1.data_ptr()

5463429091712

In [15]:
t1.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
t1.unsqueeze(0)

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [18]:
t1.unsqueeze(-1)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [19]:
torch.manual_seed(12)

In [23]:
x=torch.rand(2,10) # 2행 10열의 데이터 생성
y = torch.randint(0,2,(10,)) # 0<=x<2 범위의 정수 10개 생성
y2 = torch.randint(0,2,(2,10)) # 범위의 정수 2행 10열 생성

In [24]:
print(f"X=>{x.shape},{x.ndim}D")
print(f"y=>{y.shape},{y.ndim}D")

X=>torch.Size([2, 10]),2D
y=>torch.Size([10]),1D


In [25]:
torch.cat([x,y2], dim=1) # dim=1(열) 방향으로 연결

tensor([[0.6601, 0.0554, 0.1573, 0.8137, 0.7216, 0.2717, 0.3003, 0.6099, 0.5784,
         0.6083, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 1.0000, 1.0000, 0.0000,
         1.0000, 0.0000],
        [0.4339, 0.8813, 0.3216, 0.2604, 0.2566, 0.1872, 0.6423, 0.1786, 0.1435,
         0.7490, 0.0000, 0.0000, 0.0000, 1.0000, 1.0000, 0.0000, 1.0000, 1.0000,
         1.0000, 1.0000]])

In [26]:
torch.cat([x,y2],dim=0) # dim=0(행) 방향으로 연결

tensor([[0.6601, 0.0554, 0.1573, 0.8137, 0.7216, 0.2717, 0.3003, 0.6099, 0.5784,
         0.6083],
        [0.4339, 0.8813, 0.3216, 0.2604, 0.2566, 0.1872, 0.6423, 0.1786, 0.1435,
         0.7490],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 1.0000, 1.0000, 0.0000, 1.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 1.0000, 1.0000, 0.0000, 1.0000, 1.0000, 1.0000,
         1.0000]])

In [27]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
torch.stack([x, y, z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [28]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean()) # 전체 평균
print(t.mean(dim=0)) # 행 별 평균
print(t.mean(dim=1)) # 열 별 평균 

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


## 퍼셉트론의 연산방식

In [29]:
# ---------------------------------------------------------
# 함수명 : or_gate
# 함수기능 : OR 연산 수행  => 즉 2개 입력시 1개 이상 1이면 1
# 매개변수 : x1,x2
# 반환값 : 정수 0 또는 1
# -------------------------------------------------------
def or_gate(x1,x2):
    # 입력값 x1에 대한 가중치 w1, x2에 대한 가중치 w2
    w1, w2 = 0.6, 0.6
    
    # bias 편향값
    b = -0.5
    
    # 연산결과
    result = x1 * w1 + x2 * w2 + b
    
    # 결과가 0보다 작거나 같으면 0, 0보다 크면 1을 반환
    return 0 if result <=0 else 1

# 입력값 데이터 생성
input_list = [(0,0),(0,1),(1,0),(1,1)]
# 입력에 대한 결과 출력
for x1, x2 in input_list:
    # or_gate의 결과 저장
    or_result = or_gate(x1,x2)
    # 결과 출력
    print(f'입력값: {x1}{x2} / 결과 : {or_result}')

입력값: 00 / 결과 : 0
입력값: 01 / 결과 : 1
입력값: 10 / 결과 : 1
입력값: 11 / 결과 : 1


In [30]:
# ------------------------------------------------------
# 함수명 : and_Gate
# 함수기능 : AND 연산 수행 즉 2개 입력시 2개 모두 1인 경우만 1
# 매개변수 : x1,x2
# 반환값 : 정수 0 또는 1
# ------------------------------------------------------
def and_gate(x1,x2):
    # 입력값 x1에 대한 가중치 w1, x2에 대한 가중치 w2
    w1, w2 = 0.6, 0.6
    
    # bias 편향값
    b = -0.7
    
    # 연산결과
    result = x1 * w1 + x2 * w2 + b
    
    # 결과가 0보다 작거나 같으면 0, 0보다 크면 1을 반환
    return 0 if result <=0 else 1

# 입력값 데이터 생성
input_list = [(0, 0), (0, 1), (1, 0), (1, 1)]

# 입력에 대한 결과 출력
for x1, x2 in input_list:
    # and gate의 결과 저장
    and_result = and_gate(x1,x2)

    # 결과 출력
    print(f'입력값: {x1}{x2} / 결과: {and_result}')




입력값: 00 / 결과: 0
입력값: 01 / 결과: 0
입력값: 10 / 결과: 0
입력값: 11 / 결과: 1


In [31]:
# --------------------------------------------------------------------
# 함  수  명 : nand_gate
# 함수  기능 : NAND 연산 수행  즉, 2개 입력 시 2개 모두 1인 경우 만 1
# 매개  변수 : x1, x2
# 반  환  값 : 정수 0 또는 1
# --------------------------------------------------------------------
def nand_gate(x1, x2):
    # 입력값 x1에 대한 가중치 w1, x2에 대한 가중치 w2
    w1, w2 = 0.6, 0.6

    # bias 편향값
    b = -0.7
    # 연산 결과
    result = x1*w1 + x2*w2 + b

    # 결과가 0보다 작거나 같으면 1, 0보다 크면 0을 반환
    return 1 if result <= 0 else 0
# 입력값 데이터 생성
input_list = [(0, 0), (0, 1), (1, 0), (1, 1)]



# 입력에 대한 결과 출력
for x1, x2 in input_list:
    # and gate의 결과 저장
    nand_result = nand_gate(x1, x2)

    # 결과 출력
    print(f"입력값: {x1} {x2} / 결과: {nand_result}")

입력값: 0 0 / 결과: 1
입력값: 0 1 / 결과: 1
입력값: 1 0 / 결과: 1
입력값: 1 1 / 결과: 0
